### ISSUE TITLE
Soundness issue

### ISSUE THREAD

**Issue by Freax13** [haraldh/bash_plugin_rs#2]
`argv_list` dereferences the user accessible raw pointers `word_list::word` and `word_list::next`.

This is unsound because a user could call `argv_list` with `word_list`'s `word` and `next` fields pointing the invalid addresses and therefore cause UB.

**Comment by haraldh** [comment]
So, you want the function to be marked `unsafe` with a `# Safety` doc section?

**Comment by Freax13** [comment]
Yes, I create pull request #3.

**Comment by haraldh** [comment]
Thanks!

**Comment by haraldh** [comment]
Added a CI, more fixes, and published a new version on crates.io.

**Comment by Freax13** [comment]
Great🎊
